/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/fantasyWolf.glb -o src/conponents/FantasyWolf.jsx -k -K -r public 
Author: Jaclyn Staples (https://sketchfab.com/jaclynonacloud)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-wolf-928f0f3ce2794c7394b2586e565a6b5b
Title: Fantasy Wolf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function FantasyWolf(props) {
  const { nodes, materials } = useGLTF('/models/fantasyWolf.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="478970112c72411db1a591b82a871eadobjcleanermaterialmergergles">
            <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.material_0} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/fantasyWolf.glb')
